# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         OpenGL-Simple-GLUT
version:      0.02
version_from: GLUT.pm
installdirs:  site
requires:
    ExtUtils::Constant:            0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.21
